# This is a basic workflow to help you get started with Actions

name: Notify users based on issue labels

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: [labeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "notify"
  notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: jenschelkopf/issue-label-notification-action@1.3
        with:
          # Different labels go on different lines, for multiple people/groups space separate them
          recipients: |
            CARMA Support=@CARMAsupport
